<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CareNest.Application</RootNamespace>
    <AssemblyName>CareNest.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CareNest.Domain\CareNest.Domain.csproj" />
    <ProjectReference Include="..\CareNest.Shared\CareNest.Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
