<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <TreatWarningsAsErrors Condition="'$(CI)' == 'true'">true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>2.18.12</Version>
    <AssemblyVersion>2.18.12.0</AssemblyVersion>
    <FileVersion>2.18.12.0</FileVersion>
    <InformationalVersion>2.18.12</InformationalVersion>
    <RepositoryUrl>https://github.com/sanskarIN/CareNest</RepositoryUrl>
    <Authors>Sanskar</Authors>
    <Company>CareNest</Company>
    <Copyright>Copyright © 2026 Sanskar</Copyright>
  </PropertyGroup>
</Project>
